services:
  mariadb:
    image: mariadb:12
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_s3cr3t
      MYSQL_DATABASE: pizzaria
      MYSQL_USER: pizzaria
      MYSQL_PASSWORD: s3cr3t
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: laravel
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    entrypoint: ["sh", "./entrypoint-app.sh"]

  vite:
    build:
      context: .
      dockerfile: Dockerfile.vite
    container_name: vite
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
    ports:
      - "5173:5173"
    depends_on:
      - app
    command: sh -c "composer install && npm install && npm run dev"

volumes:
  db_data:
  vendor: