/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "login": [],
    "login.store": [],
    "logout": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "home": [],
    "dashboard": [],
    "users.index": [],
    "users.create": [],
    "users.store": [],
    "users.show": [
        {
            "name": "user",
            "required": true
        }
    ],
    "users.edit": [
        {
            "name": "user",
            "required": true
        }
    ],
    "users.update": [
        {
            "name": "user",
            "required": true
        }
    ],
    "users.destroy": [
        {
            "name": "user",
            "required": true
        }
    ],
    "roles.index": [],
    "roles.create": [],
    "roles.store": [],
    "roles.show": [
        {
            "name": "role",
            "required": true
        }
    ],
    "roles.edit": [
        {
            "name": "role",
            "required": true
        }
    ],
    "roles.update": [
        {
            "name": "role",
            "required": true
        }
    ],
    "roles.destroy": [
        {
            "name": "role",
            "required": true
        }
    ],
    "items.index": [],
    "items.create": [],
    "items.store": [],
    "items.show": [
        {
            "name": "item",
            "required": true
        }
    ],
    "items.edit": [
        {
            "name": "item",
            "required": true
        }
    ],
    "items.update": [
        {
            "name": "item",
            "required": true
        }
    ],
    "items.destroy": [
        {
            "name": "item",
            "required": true
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "user-password.edit": [],
    "user-password.update": [],
    "appearance.edit": [],
    "two-factor.show": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
