<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome TEST LINTER TEST LINTER TEST LINTER TEST LINTER TEST LINTER TEST LINTER TO FIND MISTAKES HERE TEST ANALYSER TO FIND MISTAKES HERE TEST ANALYSER TO FIND MISTAKES HERE TEST ANALYSER TO FIND MISTAKES HERE');
});
